[package]
name = "ESP8266"     # the name of the package
version = "0.0.1"       # the current version, obeying semver
authors = ["Joakim Lundberg <joakim@joakimlundberg.com>"]

[dependencies.embedded-hal]
version = "0.2.2"
features = ["unproven"]

[dependencies.nb]
version = "0.1.1"

[dependencies.heapless]
version = "0.4.0"

#[dependencies.byteorder]
#default-features = false
#version = "1.2.1"